spring:
  application:
    name: rabbitmqBoot
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-returns: true  # 消息发送到队列确认机制，是否确认回调
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    cache:
      channel:
        size: 50
server:
  port: 5555
  context-path: /