spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    publisher-confirms: true
    cache:
      channel:
        size: 50
# Define the port where the UAA server would be running
server:
  port: 7894
  # Use different context-path to avoid session cookie overlapping
  context-path: /
#  use-forward-headers: true